name: Jest CI

on:
  push:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Installation des dépendances
        # npm ci est plus rapide et strict que npm install pour la CI
        run: npm ci

      - name: 🧪 Exécution des tests Jest
        # L'argument --ci est crucial ici
        run: npm test -- --ci --coverage --maxWorkers=2

      - name: 📊 Upload du rapport de couverture
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour SonarQube (analyse de l'historique Git)

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Installation
        run: npm ci

      - name: 🧪 Tests & Coverage
        # Génère le dossier coverage/lcov.info
        run: npm test -- --ci --coverage

      - name: 🛡️ SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets:SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets:SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=25e14bebdce67ec37ec9998ca6ddcf55e1e02d71
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js